name: daily_exercises
description: dailyExercises

publish_to: 'none'



version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  counter: ^0.2.2
  kdgaugeview: ^1.0.4
  flutter_data: ^1.5.4
  import_js_library: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/foto1.png
    - assets/foto2.png
    - assets/foto3.png
    - assets/foto4.png
    - assets/foto5.png
    - assets/foto6.png
    - assets/btnfoto.jpg
    - assets/btnfoto2.jpg
    - assets/btnfoto11.jpeg
    - assets/deneme.png
    - server.js